- name: Apply MetalLB manifests
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml
  become: false

- name: Wait for MetalLB controller to be ready
  shell: |
    kubectl wait --namespace metallb-system \
      --for=condition=ready pod \
      --selector=app=metallb \
      --selector=component=controller \
      --timeout=90s
  register: wait_result
  failed_when: "'condition met' not in wait_result.stdout"
  become: false

- name: Create IPAddressPool and L2Advertisement manifest
  copy:
    dest: /tmp/metallb-config.yaml
    content: |
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: local-pool
        namespace: metallb-system
      spec:
        addresses:
          - {{ metallb_ip_range }}
      ---
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: l2-advert
        namespace: metallb-system
  become: false

- name: Apply MetalLB IP address pool configuration
  shell: kubectl apply -f /tmp/metallb-config.yaml
  become: false
