- name: Check currently installed MetalLB controller image
  command: kubectl -n metallb-system get deployment controller -o jsonpath={'.spec.template.spec.containers[0].image'}
  register: metallb_image_check
  changed_when: false
  failed_when: false

- name: Parse installed MetalLB version
  set_fact:
    installed_metallb_version: "{{ (metallb_image_check.stdout | regex_search('(v?[0-9]+\\.[0-9]+\\.[0-9]+)$')) | default('') }}"

- name: Apply MetalLB manifests
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml
  when: installed_metallb_version != metallb_version
  become: false

- name: Wait for MetalLB controller to be ready
  shell: |
    kubectl wait --namespace metallb-system \
      --for=condition=ready pod \
      --selector=app=metallb \
      --selector=component=controller \
      --timeout=90s
  register: wait_result
  failed_when: "'condition met' not in wait_result.stdout"
  become: false

- name: Create IPAddressPool and L2Advertisement manifest
  copy:
    dest: /tmp/metallb-config.yaml
    content: |
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: local-pool
        namespace: metallb-system
      spec:
        addresses:
          - {{ metallb_ip_range }}
      ---
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: l2-advert
        namespace: metallb-system
  become: false

- name: Apply MetalLB IP address pool configuration
  shell: kubectl apply -f /tmp/metallb-config.yaml
  become: false
