- name: Update system packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Configure Docker to not modify iptables
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "iptables": false
      }
    mode: '0644'
  notify: Restart Docker

- name: Add user to docker group
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes

- name: Verify Docker
  command: docker --version
  register: docker_version
  changed_when: false